-- Sudden Death shared state.
--
-- One row per pool, keyed by a league's code, the season the pool plays and
-- what its picks have to do (win or lose). A league is every row that shares a
-- code: one code, one name, one set of members, and a board for each pool it
-- was made with, so an NFL winners pool, an NFL losers pool and a college pool
-- can go to the same people as one link. Which pools a league runs is fixed
-- when it is made. Each row holds its pool's whole shared board as JSON: the
-- picks, the locks, the rules it runs on and who is in it. Realtime pushes a
-- row to every open device on change, which is what makes everyone in a league
-- see the same board.
--
-- Run this once in the Supabase SQL editor. It is safe to run again: every
-- statement checks before it acts.
--
--
-- WHAT A CODE IS, AND WHAT IT IS NOT
--
-- There are no accounts. A league's twelve-character code (see
-- src/js/core/code.js) is the credential: anyone holding one can read that
-- league and write to it, and anyone who does not know one cannot find it by
-- guessing - twelve characters from a 31-letter alphabet is about 59 bits.
--
-- What that does NOT protect against is the publishable key in src/js/config.js,
-- which every visitor's browser has to have. The policies below let that key
-- read and write rows, because a code cannot be checked by the database: the
-- client would have to send it, and a client that can send one code can send
-- another. So somebody who takes the key out of the page can read every
-- league's board, and change it. Nobody can be locked out of a league they are
-- in, nobody's picks can be lost from outside the app, and no personal data is
-- in here beyond first names people typed - but "private" is not the word for
-- it.
--
-- If that matters for your pool, the upgrade is Supabase Auth plus a
-- memberships table, with the policies below rewritten as
-- `using (auth.uid() in (select member from memberships where code = leagues.code))`.
-- That is a real change: people would have to sign in, and joining would become
-- an invitation rather than a code. This file is deliberately the simpler
-- trade, and it is written down here so it is a choice rather than a surprise.

create table if not exists public.leagues (
  code        text not null,
  name        text not null,
  sport       text not null,
  objective   text not null default 'win',
  entry       jsonb not null default '{"picks":{},"swaps":{}}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (code, sport, objective)
);

-- Tables from before the objective was a column carried it inside the board's
-- rules. Lift it out once, so a losers league made back then stays one, and so
-- an NFL winners pool and an NFL losers pool can sit under one code. Guarded:
-- a re-run finds the column and leaves it alone.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'leagues' and column_name = 'objective'
  ) then
    alter table public.leagues add column objective text not null default 'win';
    update public.leagues set objective = 'lose' where entry->'rules'->>'objective' = 'lose';
  end if;
end $$;

alter table public.leagues drop constraint if exists leagues_objective_known;
alter table public.leagues
  add constraint leagues_objective_known check (objective in ('win', 'lose'));

-- Tables made before a league could hold more than one pool keyed the row on
-- the code alone. Re-key them on (code, sport, objective) so more pools can sit
-- under a league; every existing row keeps working, since it is still the only
-- one with its code. Guarded so a re-run finds the key already right and does
-- nothing.
do $$
declare
  key_columns text;
begin
  select string_agg(a.attname, ',' order by k.ordinality)
    into key_columns
    from pg_constraint c
    join lateral unnest(c.conkey) with ordinality as k(attnum, ordinality) on true
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum
   where c.conrelid = 'public.leagues'::regclass and c.contype = 'p';

  if key_columns is distinct from 'code,sport,objective' then
    execute 'alter table public.leagues drop constraint if exists leagues_pkey';
    execute 'alter table public.leagues add primary key (code, sport, objective)';
  end if;
end $$;

-- Codes are generated by the app, in one shape, and a row that is not in it is
-- a row nothing can open: twelve characters, no I, L, O, 0 or 1.
alter table public.leagues drop constraint if exists leagues_code_shape;
alter table public.leagues
  add constraint leagues_code_shape check (code ~ '^[2-9A-HJKMNP-Z]{12}$');

-- The season a pool plays has to be one the repo carries data for, or its
-- board has nothing to price. Add to this list when you add a folder under
-- data/ and an entry in src/js/sports.js.
alter table public.leagues drop constraint if exists leagues_sport_known;
alter table public.leagues
  add constraint leagues_sport_known check (sport in ('nfl', 'cfb'));

-- Finding a league by code is the app's only lookup, and it walks the first
-- column of the primary key. This index is for the housekeeping query below.
create index if not exists leagues_updated_at_idx on public.leagues (updated_at desc);

-- Realtime so a pick on one phone lands on the others. Guarded, because adding
-- a table that is already in the publication is an error, and one error aborts
-- the whole script on a re-run.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'leagues'
  ) then
    alter publication supabase_realtime add table public.leagues;
  end if;
end $$;

-- Realtime sends the whole row on an update, so the board gets the new state
-- rather than a diff it would have to fetch.
alter table public.leagues replica identity full;

alter table public.leagues enable row level security;

-- Without this the publishable key's role cannot reach the table at all and
-- every read and write is refused before the policies are even consulted.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.leagues to anon, authenticated;

-- Policy names from earlier versions of this file, so a re-run replaces them.
drop policy if exists "read shared entry" on public.leagues;
drop policy if exists "insert shared entry" on public.leagues;
drop policy if exists "update shared entry" on public.leagues;
drop policy if exists "read league entries" on public.leagues;
drop policy if exists "insert league entries" on public.leagues;
drop policy if exists "update league entries" on public.leagues;

-- Read and write for anyone with the key, which is everyone who opens the
-- page: see the note at the top. The app only ever asks for one code at a
-- time, and a league's code is what makes it findable.
drop policy if exists "read leagues" on public.leagues;
create policy "read leagues" on public.leagues for select using (true);

drop policy if exists "create leagues" on public.leagues;
create policy "create leagues" on public.leagues for insert with check (true);

drop policy if exists "write leagues" on public.leagues;
create policy "write leagues" on public.leagues for update using (true) with check (true);

-- Delete, for the settings sheet's "Remove this pool" and "Delete league". A
-- row going takes everyone's season on it, so the app asks twice before it
-- sends one; but the trust is the same the code already carries - whoever can
-- rewrite every pick on a board can take the board down - and a league whose
-- season is over, or was made by mistake, should not need this editor to go.
-- Leaving a league is still a local act (see src/js/store/directory.js).
drop policy if exists "delete leagues" on public.leagues;
create policy "delete leagues" on public.leagues for delete using (true);

-- The old table, from when the three pools were built into the app and their
-- ids were the row keys. Nothing reads it any more. Drop it when you have
-- looked at what is in it - the picks from those pools are the only copy:
--
--   select id, entry from public.entries;
--   drop table public.entries;

-- The API layer caches the table's shape and can go on serving the old one
-- after the changes above, refusing a column it has not heard of ("Could not
-- find the 'objective' column of 'leagues' in the schema cache"). Ask it to
-- look again, so the app works the moment this file has run.
notify pgrst, 'reload schema';
