-- Survivor Board shared state.
--
-- One row per league, keyed by the league's code. The row holds the league's
-- name, the season it plays, and its whole shared board as JSON: the picks,
-- the locks, the rules it runs on and who is in it. Realtime pushes the row to
-- every open device on change, which is what makes everyone in a league see
-- the same board.
--
-- Run this once in the Supabase SQL editor. It is safe to run again: every
-- statement checks before it acts.
--
--
-- WHAT A CODE IS, AND WHAT IT IS NOT
--
-- There are no accounts. A league's twelve-character code (see
-- src/js/core/code.js) is the credential: anyone holding one can read that
-- league and write to it, and anyone who does not know one cannot find it by
-- guessing - twelve characters from a 31-letter alphabet is about 59 bits.
--
-- What that does NOT protect against is the publishable key in src/js/config.js,
-- which every visitor's browser has to have. The policies below let that key
-- read and write rows, because a code cannot be checked by the database: the
-- client would have to send it, and a client that can send one code can send
-- another. So somebody who takes the key out of the page can read every
-- league's board, and change it. Nobody can be locked out of a league they are
-- in, nobody's picks can be lost from outside the app, and no personal data is
-- in here beyond first names people typed - but "private" is not the word for
-- it.
--
-- If that matters for your pool, the upgrade is Supabase Auth plus a
-- memberships table, with the policies below rewritten as
-- `using (auth.uid() in (select member from memberships where code = leagues.code))`.
-- That is a real change: people would have to sign in, and joining would become
-- an invitation rather than a code. This file is deliberately the simpler
-- trade, and it is written down here so it is a choice rather than a surprise.

create table if not exists public.leagues (
  code        text primary key,
  name        text not null,
  sport       text not null,
  entry       jsonb not null default '{"picks":{},"swaps":{}}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Codes are generated by the app, in one shape, and a row that is not in it is
-- a row nothing can open: twelve characters, no I, L, O, 0 or 1.
alter table public.leagues drop constraint if exists leagues_code_shape;
alter table public.leagues
  add constraint leagues_code_shape check (code ~ '^[2-9A-HJKMNP-Z]{12}$');

-- The season a league plays has to be one the repo carries data for, or its
-- board has nothing to price. Add to this list when you add a folder under
-- data/ and an entry in src/js/sports.js.
alter table public.leagues drop constraint if exists leagues_sport_known;
alter table public.leagues
  add constraint leagues_sport_known check (sport in ('nfl', 'cfb'));

-- Finding a league by code is the app's only lookup, and it is a primary key
-- hit. This index is for the housekeeping query below.
create index if not exists leagues_updated_at_idx on public.leagues (updated_at desc);

-- Realtime so a pick on one phone lands on the others. Guarded, because adding
-- a table that is already in the publication is an error, and one error aborts
-- the whole script on a re-run.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'leagues'
  ) then
    alter publication supabase_realtime add table public.leagues;
  end if;
end $$;

-- Realtime sends the whole row on an update, so the board gets the new state
-- rather than a diff it would have to fetch.
alter table public.leagues replica identity full;

alter table public.leagues enable row level security;

-- Without this the publishable key's role cannot reach the table at all and
-- every read and write is refused before the policies are even consulted.
grant usage on schema public to anon, authenticated;
grant select, insert, update on public.leagues to anon, authenticated;

-- Policy names from earlier versions of this file, so a re-run replaces them.
drop policy if exists "read shared entry" on public.leagues;
drop policy if exists "insert shared entry" on public.leagues;
drop policy if exists "update shared entry" on public.leagues;
drop policy if exists "read league entries" on public.leagues;
drop policy if exists "insert league entries" on public.leagues;
drop policy if exists "update league entries" on public.leagues;

-- Read and write for anyone with the key, which is everyone who opens the
-- page: see the note at the top. The app only ever asks for one code at a
-- time, and a league's code is what makes it findable.
drop policy if exists "read leagues" on public.leagues;
create policy "read leagues" on public.leagues for select using (true);

drop policy if exists "create leagues" on public.leagues;
create policy "create leagues" on public.leagues for insert with check (true);

drop policy if exists "write leagues" on public.leagues;
create policy "write leagues" on public.leagues for update using (true) with check (true);

-- Deliberately no delete policy. With one shared board per league, deleting a
-- row takes everyone's season with it, and that is not something a phone
-- should be able to do. Leaving a league is a local act (see
-- src/js/store/directory.js); clearing one out is a job for this editor.

-- The old table, from when the three pools were built into the app and their
-- ids were the row keys. Nothing reads it any more. Drop it when you have
-- looked at what is in it - the picks from those pools are the only copy:
--
--   select id, entry from public.entries;
--   drop table public.entries;
